export const SCENE_KEYS = {
  PRELOAD_SCENE: 'PRELOAD_SCENE',
  GAME_SCENE: 'GAME_SCENE',
  UI_SCENE: 'UI_SCENE',
  GAME_OVER_SCENE: 'GAME_OVER_SCENE',
  START_SCENE: 'START_SCENE',
  OPTIONS_SCENE: 'OPTIONS_SCENE',
  TOUCH_CONTROLS_SCENE: 'TOUCH_CONTROLS_SCENE',
} as const;
